import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 30,
    marginBottom: 15,
  },
  title: {
    fontSize: 25,
    fontWeight: 'bold',
    color: '#1F2937',
    textAlign: 'center',
    flex: 1,
  },
  welcomeText: {
    fontSize: 20,
    fontWeight: '500',
    color: '#1F2937',
    textAlign: 'center',
    marginVertical: 40,
    marginTop: 60,
  },
  primaryButton: {
    width: '90%',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    alignItems: 'center',
    marginBottom: 20, // Reduced margin to fit the new button
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginTop: 5,
    marginBottom: 5,
    textAlign: 'center',
  },
  primaryButtonSubtitle: {
    fontSize: 14,
    color: '#1F2937',
    textAlign: 'center',
  },
  secondaryButton: {
    width: '90%',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 20,
    elevation: 3, // Slightly less elevation for a lighter shadow
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    alignItems: 'center',
    marginBottom: 30,
  },
  secondaryButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginTop: 5,
    marginBottom: 5,
    textAlign: 'center',
  },
  secondaryButtonSubtitle: {
    fontSize: 14,
    color: '#6B7280', // Lighter color to differentiate from primary button
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 15,
    width: '80%',
    alignItems: 'center',
    elevation: 5,
  },
  modalIcon: {
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 5,
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#1F2937',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalButton: {
    width: '100%',
    paddingVertical: 12,
    backgroundColor: '#000',
    borderRadius: 8,
    marginBottom: 10,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '600',
  },
  signOutButton: {
    position: 'absolute',
    left: -23,
    padding: 10,
  },
  centeredContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
});